version: 2

updates:
  # 루트 package.json 의존성 관리
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    reviewers:
      - "jun094"  # 실제 GitHub 사용자명으로 변경
    assignees:
      - "jun094"  # 실제 GitHub 사용자명으로 변경
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    
  # figma-connector 앱 의존성 관리
  - package-ecosystem: "npm"
    directory: "/apps/figma-connector"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "jun094"
    assignees:
      - "jun094"
    commit-message:
      prefix: "deps(harvester)"
      include: "scope"
    labels:
      - "dependencies"
      - "harvester"
      - "automated"
    
  # shared-types 패키지 의존성 관리
  - package-ecosystem: "npm"
    directory: "/packages/shared-types"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "jun094"
    assignees:
      - "jun094"
    commit-message:
      prefix: "deps(types)"
      include: "scope"
    labels:
      - "dependencies"
      - "types"
      - "automated"

  # GitHub Actions 워크플로우 의존성 관리
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    reviewers:
      - "jun094"
    assignees:
      - "jun094"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci"
      - "automated"
