name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.11.1
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Type check
      run: pnpm typecheck
      
    - name: Lint
      run: pnpm lint
      
    - name: Build
      run: pnpm build
      
    # TODO: 테스트 추가 후 활성화
    # - name: Test
    #   run: pnpm test
    #   
    # - name: Test Coverage
    #   run: pnpm test:coverage

  build-and-test-apps:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.11.1
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build harvester app
      run: pnpm build:harvester
      
    - name: Build types package
      run: pnpm build:types
      
    - name: Check if harvester starts successfully
      run: |
        # 환경변수 없이도 기본적인 구동 확인
        timeout 10s pnpm start:harvester || test $? -eq 124

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.11.1
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Security audit
      run: pnpm audit --audit-level moderate
      
    - name: Check for known vulnerabilities
      run: |
        # 추가 보안 체크를 위한 공간
        echo "Security check completed"
